import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import client from '../../apolloClient';
import { gql } from '@apollo/client';
import Link from 'next/link';


export default function Home(posts) {
  posts = posts.posts;
  return (
    <>
      <Head>
        <title>Travel itinerary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.background}></div>
        <div className={styles.description}>
          <h3>
            Laboration 3
          </h3>
          <p>Sweden</p>
        </div>
        <h1 className={styles.title1}>
            Travel itinerary
        </h1>
        <ul className={styles.list}>
          {posts && posts.map( (post, i) => <li key={i}><Link href={`/posts/${post.slug}`}>{post.title}</Link></li>)}
        </ul>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const {data} = await client.query({
    query: gql`
    query MyQuery {
      posts {
        id
        guestName
        slug
        title
        postDate
        publishedAt
        description {
          raw
          html
        }
        coverImage {
          url
        }
      }
    }`
  })
  const {posts} = data;
  return {
    props: {
      posts
    }
  }
}